### ISSUE TITLE
Marketing Qualified Reason and MQL Date Operations

### ISSUE THREAD

**Issue by cfinsness** [artsy/clouds#13]
Desired output (sample) - 

<img width="549" alt="screen shot 2017-07-21 at 5 04 08 pm" src="https://user-images.githubusercontent.com/6314270/28482500-a94f62da-6e36-11e7-93e2-0cbeb65f4f68.png">

**Comment by nicholassewitz** [comment]
https://artsy.looker.com/x/tuhB7HEecrXQWL1ddsELKk

**Comment by nicholassewitz** [comment]
Seems like there are still some items here to do

- If SAL,SQO,IOO then mark reason as Manually Accepted by Sales
- Clean up Historic Data

**Comment by nicholassewitz** [comment]
After a very long ongoing conversation we have decided to

- Stamp MQL First and Recent Date when lifecycle is changed to SAL,SQO,IOO AND MQL First is null
- Change MQL Reason to Manually Accepted by Sales when lifecycle is changed to SAL,SQO,IOO AND MQL reason is null

**Comment by nicholassewitz** [comment]
I've created a workflow rule on the patron for the date and the contact for the reason ^

**Comment by cfinsness** [comment]
can you link to the workflow? @nicholassewitz

**Comment by nicholassewitz** [comment]
linked above

**Comment by nicholassewitz** [comment]
- This [lead](https://artsy.my.salesforce.com/a18C0000006lbwI) was SAL when they applied so that then the MQL date was not filled in since lifecycle was not changed
- This [lead](https://artsy.my.salesforce.com/003C0000025QBKR) was IOO when they applied so that then the MQL date was not filled in since lifecycle was not changed. 

Should we set up a workflow to move anyone in SAL, SQO, or IOO to MAL after 90 days in the same stage

**Comment by cfinsness** [comment]
@nicholassewitz yes that makes sense, can you set that up?

**Comment by nicholassewitz** [comment]
will do
