### ISSUE TITLE
Create rule to update Partner Type if self-identifies over marketo form

### ISSUE THREAD

**Issue by nicholassewitz** [artsy/clouds#46]

**Comment by nicholassewitz** [comment]
is this done?

**Comment by cfinsness** [comment]
no because we can't update an account field from marketo, so need another solution. will take a look this week.

**Comment by nicholassewitz** [comment]
got it thought this was something else. no rush

**Comment by cfinsness** [comment]
Running through these old issues. Marketo cannot update fields on the account level. From spot checking, partner type should be more accurate than type since that is assumably checked by a human. May revisit later if we do account cleaning, but will close from now since it doesn't seem like an extensive / pressing issue.
