### ISSUE TITLE
Active Partner Patrons showing up in List Views

### ISSUE THREAD

**Issue by nicholassewitz** [artsy/clouds#70]
https://artsy.my.salesforce.com/003C000001xlTsv

There are 7900 contacts that are attached to active partners that have a lifecycle of MAL or MQL. Should that be the case?

**Comment by cfinsness** [comment]
@nicholassewitz the account subscription state = inactive
https://artsy.my.salesforce.com/001C000001PbvJZ
which is why they might have appeared. 

Fixes to do are still: 
- [ ] Troubleshoot why Won leads do not have open opp date https://artsy.my.salesforce.com/00OC0000006q3A0
- [ ] Switch anyone with active subscription state, attached to an opp, to Won https://artsy.my.salesforce.com/00OC0000006q3A5

**Comment by cfinsness** [comment]
(We still want closed/won stage to be on the individual level, not the account level as we talked about earlier. The only exception to stage being update from an account state is "not in model")

**Comment by cfinsness** [comment]
@nicholassewitz closed this issue but couldn't update these leads bc of an error 
https://docs.google.com/spreadsheets/d/19k3S07WxZto7m4pfFvjbdvQcJG2wTHWAdu-BCwjYH9U/edit#gid=0
This is related to part 2 above (from your sql query)

**Comment by nicholassewitz** [comment]
updated the error ones. we had to disable the process that updates the account lifecycle.
