### ISSUE TITLE
MQL Alert Email going out before properly assigned

### ISSUE THREAD

**Issue by nicholassewitz** [artsy/clouds#71]
Seems like the MQL email is still going out to early. Looking at their activity history it is hard to decipher what happened here @cfinsness ?

https://artsy.my.salesforce.com/003C000002D7aAx?srPos=0&srKp=003

https://app-ab14.marketo.com/access/leadDetail?sfdcContactId=003C000002D7aAxIAJ&tok=xVoNJZWbUlUb7x4muazAcPuh3SbGfpuLtLJpCPTy%2B8t8gwouIr%2FsaBG%2F2IMDOMUzRPG3IChSX9JywQBdCdWGeZJp%2FrcHSRHiDRiv0PGKP91vIJZQ0OhA0erpmmMXr9mHnEjFCENMGjNqZzSYebAykAvuNYdhE0GS6X7THINhxmoPkLgXwrKqb6f6%2BHyttwiE4TqKIV14ppvZ50%2B1TtUons8RtlMh%2BxJ8LLWmsGySku1z%2Fjs%3D

**Comment by cfinsness** [comment]
It looks like there was a 17 minute delay between them applying and being reassigned. We only had a 10 minute wait step between reassignment and the alert -  https://app-ab14.marketo.com/#SC2086C3
I have changed this to be 20 minutes. Very odd because I thought we had a longer wait step there previously. 

Note that this lead applied TWICE on the same day which is why they were later assigned to Jordana.
