### ISSUE TITLE
MQL Fills out form Twice in a Row

### ISSUE THREAD

**Issue by nicholassewitz** [artsy/clouds#73]
This lead https://artsy.my.salesforce.com/003C000002D7YkP filled out an application form twice within 10 minutes of each other. It caused the flow to mess up and reassign the lead twice as well as send out multiple mql emails. 

Should we add a 10 minute filter to the application campaign?

**Comment by cfinsness** [comment]
@nicholassewitz This seems very edge casey but I've changed this campaign so that leads can only qualify for it once an hour https://app-ab14.marketo.com/#SC2086E5 

Do you think this is enough time? We could also consider adding a rule to only reassign if there hasn't been any very recent GP activity logged - so that if someone has already tried reaching out to them they are not passed onto someone else. Lmk.

**Comment by nicholassewitz** [comment]
I think the once in an hour works in theory. Lets see how it plays out.
